// auth user actions
export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START';
export const EMAIL_SIGN_IN_START = 'EMAIL_SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const CHECK_USER_SESION = 'CHECK_USER_SESION';
export const SIGN_OUT_USER_START = 'SIGN_OUT_USER_START';
export const SIGN_OUT_USER_SUCCESS = 'SIGN_OUT_USER_SUCCESS';
export const SIGN_OUT_USER_FAILURE = 'SIGN_OUT_USER_FAILURE';
export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

// cart acitons
export const TOGGLE_HIDDEN = 'TOGGLE_HIDDEN';
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const DECREASE_ITEM_QUANTITY = 'DECREASE_ITEM_QUANTITY';
export const CLEAR_CART = 'CLEAR_CART';

// directory actions
export const GET_DIRECTORY_SECTIONS = 'GET_DIRECTORY_SECTIONS';

// shop actions

export const UPDATE_COLLECTIONS = 'UPDATE_COLLECTIONS';
export const FETCH_COLLECTIONS_START = 'FETCH_COLLECTION_START';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTION_SUCCESS';
export const FETCH_COLLECTIONS_FAILURE = 'FETCH_COLLECTION_FAILURE';
